name: notebook-services

services:
  notebook:
    build: 
      context: .
      target: development
    ports: 
      - 3000:80
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTEBOOK_DB_USER}:${NOTEBOOK_DB_PASSWORD}@notebook-db/${NOTEBOOK_DB_NAME}
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    networks: 
      - notebook-net
    depends_on: 
      - notebook-db

  notebook-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notebook-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
    networks: 
      - notebook-net

volumes:
  notebook-data:

networks:
  notebook-net: